import G3Tool.Parse

/-!
# The table module `FrogModel/G3K/Table.lean` of the kernel checker

Written from the version 3 table by `g3ktable`. Each lookup by a child state or a phase is written
twice: a readable form with `if` (used by the reference checker `FrogModel.G3K.Spec`, which `g3k`
also runs compiled) and a kernel form with `Bool.rec` on `Nat.ble` (suffix `F`, used by
`FrogModel.G3K.Fast`), with a proof of their equality. Out of range arguments get the last leaf
(child state 37, phase J). Untrusted: the soundness proof reads the tables against the child
chain of the frozen statement.
-/

namespace G3Tool

/-- A balanced tree over `[lo, hi)` in the variable `x`: `if` form. -/
partial def ifTree (lo hi : Nat) (leaf : Nat → String) (x : String) : String :=
  if hi ≤ lo + 1 then leaf lo else
  let mid := (lo + hi) / 2
  s!"(if {mid} ≤ {x} then {ifTree mid hi leaf x} else {ifTree lo mid leaf x})"

/-- The same tree as `Bool.rec` on `Nat.ble`, values of type `ty`. -/
partial def recTree (ty : String) (lo hi : Nat) (leaf : Nat → String) (x : String) : String :=
  if hi ≤ lo + 1 then leaf lo else
  let mid := (lo + hi) / 2
  s!"(Bool.rec (motive := fun _ => {ty}) {recTree ty lo mid leaf x} {recTree ty mid hi leaf x} (Nat.ble (nat_lit {mid}) {x}))"

def lit (n : Nat) : String := s!"(nat_lit {n})"

def triplesLit (l : List (Nat × Nat × Nat)) : String :=
  "[" ++ ", ".intercalate (l.map fun (a, b, s) => s!"({lit a}, {lit b}, {lit s})") ++ "]"

def tableModuleK (tb : Table) (ch : Chain) (sha : String) : String := Id.run do
  let j := tb.j
  let t := tb.t
  let th5 := Q.div ch.theta (Q.ofNat 5)
  let n := ch.names.size
  let mut out := s!"module\n\npublic import FrogModel.G3K.Basic\n\n@[expose] public section\n\n/-! Generated by `g3k table` from the table with sha256 {sha}.\nChild states:\n"
  for i in [0:n] do out := out ++ s!"{i} {ch.names[i]!}\n"
  out := out ++ "-/\n\nnamespace FrogModel.G3K\n\n"
  out := out ++ s!"def cJ : Nat := {lit j}\ndef cT : Nat := {lit t}\ndef cTP : Nat := {lit tb.tp}\n"
  out := out ++ s!"def epsN : Nat := {lit tb.eps.n}\ndef epsD : Nat := {lit tb.eps.d}\n"
  out := out ++ s!"def rhoN : Nat := {lit tb.rho.n}\ndef rhoD : Nat := {lit tb.rho.d}\n"
  out := out ++ s!"def phiN : Nat := {lit tb.phi.n}\ndef phiD : Nat := {lit tb.phi.d}\n"
  out := out ++ s!"/-- theta / 5 -/\ndef th5N : Nat := {lit th5.n}\ndef th5D : Nat := {lit th5.d}\n"
  out := out ++ s!"/-- floor(2^48 / 5) -/\ndef exitLo : Nat := {lit (Q.floor48 (Q.div Q.one (Q.ofNat 5)))}\n"
  out := out ++ s!"/-- ceil(2^48 theta / 5) -/\ndef exitHi : Nat := {lit (Q.ceil48 th5)}\n\n"
  for c in [0:n] do
    let rs := ch.rows[c]!.toList.map fun r =>
      let o := Q.div r.p (Q.ofNat 5)
      s!"Tr.mk {lit o.n} {lit o.d} {lit r.delta} {lit r.next}"
    out := out ++ s!"def row{c} : List Tr := [{", ".intercalate rs}]\n"
  out := out ++ s!"\n/-- The row of the child state `c`. -/\ndef row (c : Nat) : List Tr :=\n  {ifTree 0 n (fun i => s!"row{i}") "c"}\n"
  out := out ++ s!"noncomputable def rowF (c : Nat) : List Tr :=\n  {recTree "List Tr" 0 n (fun i => s!"row{i}") "c"}\n"
  out := out ++ s!"\n/-- The numerator of the potential of `c`. -/\ndef wN (c : Nat) : Nat :=\n  {ifTree 0 n (fun i => lit ch.w[i]!.n) "c"}\n"
  out := out ++ s!"noncomputable def wNF (c : Nat) : Nat :=\n  {recTree "Nat" 0 n (fun i => lit ch.w[i]!.n) "c"}\n"
  out := out ++ s!"\n/-- The denominator of the potential of `c`. -/\ndef wD (c : Nat) : Nat :=\n  {ifTree 0 n (fun i => lit ch.w[i]!.d) "c"}\n"
  out := out ++ s!"noncomputable def wDF (c : Nat) : Nat :=\n  {recTree "Nat" 0 n (fun i => lit ch.w[i]!.d) "c"}\n"
  let lumpTab := (List.range n).foldr (fun i acc => acc * 64 + ch.lump[i]!) 0
  out := out ++ s!"\n/-- The lumps of the child states, `lump c` the base-64 digit `c`. -/\ndef lumpTab : Nat := {lit lumpTab}\n"
  out := out ++ "/-- The lump of the child state `c` (0 for `c` out of range). -/\ndef lumpC (c : Nat) : Nat := lumpTab / 64 ^ c % 64\n"
  out := out ++ s!"\n/-- The tail state reached from `F` (`c = 0`) or `B`. -/\ndef tailOf (c : Nat) : Nat := if c = 0 then {lit ch.tailF} else {lit ch.tailB}\n"
  -- phases
  out := out ++ "\n/-- The lane data of a phase: lanes, guard bits, the mask of the bounds of V', and the gathers of
the exit (`gx`) and of the end of the phase (`cp0`, `cp1`), lanes `[a, b)` moved up by `s` lanes. -/
structure Ph where
  nL : Nat
  gV : Nat
  lowV : Nat
  gx : List (Nat × Nat × Nat)
  cp0 : List (Nat × Nat × Nat)
  cp1 : List (Nat × Nat × Nat)

/-- Bit 95 of each of `n` lanes of 96 bits. -/
def gVof (n : Nat) : Nat := 2 ^ 95 * ((2 ^ (96 * n) - 1) / (2 ^ 96 - 1))
/-- Bits 0 to 46 of each of `n` lanes of 96 bits. -/
def lowVof (n : Nat) : Nat := (2 ^ 47 - 1) * ((2 ^ (96 * n) - 1) / (2 ^ 96 - 1))\n\n"
  for q in [0:j + 1] do
    let nl := if q == 0 then 0 else binom (t + j - q + 1) (j - q + 1)
    let gx := if q == 0 then [] else gxList j t q
    let c0 := if q == 0 then [] else cpList j t q 0
    let c1 := if q == 0 then [] else cpList j t q 1
    out := out ++ s!"def ph{q} : Ph := ⟨{lit nl}, gVof {lit nl}, lowVof {lit nl}, {triplesLit gx}, {triplesLit c0}, {triplesLit c1}⟩\n"
  out := out ++ s!"\n/-- The lane data of phase `q`. -/\ndef phase (q : Nat) : Ph :=\n  {ifTree 0 (j + 1) (fun q => s!"ph{q}") "q"}\n"
  out := out ++ s!"noncomputable def phaseF (q : Nat) : Ph :=\n  {recTree "Ph" 0 (j + 1) (fun q => s!"ph{q}") "q"}\n"
  out := out ++ "\ntheorem rowF_eq : rowF = row := by funext c; simp only [rowF, row, ite_le]\n"
  out := out ++ "theorem wNF_eq : wNF = wN := by funext c; simp only [wNF, wN, ite_le]\n"
  out := out ++ "theorem wDF_eq : wDF = wD := by funext c; simp only [wDF, wD, ite_le]\n"
  out := out ++ "theorem phaseF_eq : phaseF = phase := by funext q; simp only [phaseF, phase, ite_le]\n"
  out := out ++ "\nend FrogModel.G3K\n"
  return out

end G3Tool
