module

public import FrogModel.Recursion.Process
public import FrogModel.Pieces.Stage

@[expose] public section

/-!
# Root arrivals of a closure (Lemma 4.3 of the paper)

Units `x : α` with pieces `π x : P`; `gen x (π x) y`: unit `x` generates unit `y`. The active
units are `Stage.closure gen π (init '' {a | a < j})`. The units split into root units
(`isRoot`) and units of the subtree of child `c` (`sub c`). A root unit of direction `0`
generates nothing; a root unit of direction `c.succ` and a unit of subtree `c` generate only
root units and units of subtree `c`.

- `subClosure c S`: the closure, through arcs into subtree `c`, of the root units of `S` of
  direction `c.succ` (the entries of `S` into `c`).
- `outGen c S`: the root units generated by `subClosure c S` (the returns of child `c`).
- `arrSet_eq_closure`: the active root units are `arrSet init dir outGen j` (Process.lean).
-/

open FrogModel.LemmaX

namespace FrogModel.Recursion

/-- The closure in subtree `c` of the entries of `S` into `c`. -/
def subClosure {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1)) (gen : α → P → α → Prop)
    (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop) (c : Fin d) (S : Set α) :
    Set α :=
  FrogModel.Stage.closure (fun x p y => gen x p y ∧ sub c y) π
    {x | x ∈ S ∧ isRoot x ∧ dir x = c.succ}

/-- The root units returned by child `c` given the units `S`. -/
def outGen {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1)) (gen : α → P → α → Prop)
    (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop) (c : Fin d) (S : Set α) :
    Set α :=
  {y | isRoot y ∧ ∃ x ∈ subClosure dir gen π isRoot sub c S, gen x (π x) y}

/-! ### The subtree closure -/

/-- The subtree closure is monotone. -/
theorem subClosure_mono {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1)) (gen : α → P → α → Prop)
    (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop) (c : Fin d) :
    Monotone (subClosure dir gen π isRoot sub c) := by
  intro S S' h
  unfold subClosure
  apply Set.sInter_subset_sInter
  intro T hT
  rcases hT with ⟨hbase, hclosed⟩
  refine ⟨?_, hclosed⟩
  intro x hx
  rcases hx with ⟨hxS, hxRoot, hxDir⟩
  exact hbase ⟨h hxS, hxRoot, hxDir⟩

/-- The returns of a child are monotone in the units given. -/
theorem outGen_mono {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1)) (gen : α → P → α → Prop)
    (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop) (c : Fin d) :
    Monotone (outGen dir gen π isRoot sub c) := by
  intro S S' h
  intro y hy
  rcases hy with ⟨hisRoot, x, hx, hgen⟩
  have hx' : x ∈ subClosure dir gen π isRoot sub c S' :=
    (subClosure_mono dir gen π isRoot sub c h) hx
  exact ⟨hisRoot, x, hx', hgen⟩

/-- The subtree closure holds the entries and units of the subtree only. -/
theorem subClosure_subset {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (c : Fin d) (S : Set α) :
    subClosure dir gen π isRoot sub c S ⊆
      {x | (x ∈ S ∧ isRoot x ∧ dir x = c.succ) ∨ sub c x} := by
  unfold subClosure
  refine Set.sInter_subset_of_mem ?_
  refine ⟨?base, ?arc⟩
  · -- base ⊆ R
    intro x hx
    rcases hx with ⟨hxS, hxRoot, hxDir⟩
    exact Or.inl ⟨hxS, hxRoot, hxDir⟩
  · -- closure under arcs
    intro σ hσ τ hτ
    rcases hτ with ⟨hgen, hsub⟩
    exact Or.inr hsub

/-- No initial unit is returned. -/
theorem init_not_mem_outGen {d : ℕ} {α P : Type*} (init : ℕ → α) (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (hinitGen : ∀ x a, ¬ gen x (π x) (init a)) (c : Fin d) (S : Set α) (a : ℕ) :
    init a ∉ outGen dir gen π isRoot sub c S := by
  intro h
  simp [outGen] at h
  rcases h with ⟨_, x, _, hgen⟩
  exact hinitGen x a hgen

/-- Two children return disjoint sets, if a root unit has at most one generator. -/
theorem outGen_disjoint {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (hsubRoot : ∀ c x, sub c x → ¬ isRoot x) (hsubDisj : ∀ c c' x, sub c x → sub c' x → c = c')
    (hpred : ∀ x x' y, isRoot y → gen x (π x) y → gen x' (π x') y → x = x')
    (c c' : Fin d) (S S' : Set α) (hcc : c ≠ c') :
    Disjoint (outGen dir gen π isRoot sub c S) (outGen dir gen π isRoot sub c' S') := by
  rw [Set.disjoint_left]
  intro y hy hy'
  rcases hy with ⟨hyRoot, x, hx, hgen⟩
  rcases hy' with ⟨hyRoot', x', hx', hgen'⟩
  have hx_eq : x = x' := hpred x x' y hyRoot hgen hgen'
  subst hx_eq
  have hsub := subClosure_subset dir gen π isRoot sub c S hx
  have hsub' := subClosure_subset dir gen π isRoot sub c' S' hx'
  rcases hsub with (⟨hxS, hxRoot, hxDir⟩ | hxSub)
  · rcases hsub' with (⟨hxS', hxRoot', hxDir'⟩ | hxSub')
    · -- both dir x = c.succ and dir x = c'.succ
      have h_succ_eq : c.succ = c'.succ := by
        rw [← hxDir, hxDir']
      have hc_eq : c = c' := (Fin.succ_inj).mp h_succ_eq
      exact hcc hc_eq
    · -- dir x = c.succ and sub c' x
      exact hsubRoot c' x hxSub' hxRoot
  · rcases hsub' with (⟨hxS', hxRoot', hxDir'⟩ | hxSub')
    · -- sub c x and dir x = c'.succ
      exact hsubRoot c x hxSub hxRoot'
    · -- sub c x and sub c' x
      have hc_eq : c = c' := hsubDisj c c' x hxSub hxSub'
      exact hcc hc_eq

/-! ### The active root units -/

/-- If the entries of `S` into `c` are active, so is their subtree closure. -/
theorem subClosure_subset_closure {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (I : Set α) (c : Fin d) (S : Set α) (hS : S ⊆ FrogModel.Stage.closure gen π I) :
    subClosure dir gen π isRoot sub c S ⊆ FrogModel.Stage.closure gen π I := by
  set C := FrogModel.Stage.closure gen π I
  set base' : Set α := {x | x ∈ S ∧ isRoot x ∧ dir x = c.succ}
  have hbase' : base' ⊆ C := by
    intro x hx
    rcases hx with ⟨hxS, _, _⟩
    exact hS hxS
  have hC_closed : ∀ σ ∈ C, ∀ τ, (gen σ (π σ) τ ∧ sub c τ) → τ ∈ C := by
    intro σ hσ τ ⟨hgen, _⟩
    intro U hU
    have hU_mem : I ⊆ U ∧ ∀ σ' ∈ U, ∀ τ', gen σ' (π σ') τ' → τ' ∈ U := hU
    rcases hU_mem with ⟨hIU, hUclosed⟩
    have hσU : σ ∈ U := (Set.mem_sInter.mp hσ) U hU
    exact hUclosed σ hσU τ hgen
  have hC_mem : C ∈ {T | base' ⊆ T ∧ ∀ σ ∈ T, ∀ τ, (gen σ (π σ) τ ∧ sub c τ) → τ ∈ T} :=
    ⟨hbase', hC_closed⟩
  unfold subClosure
  exact Set.sInter_subset_of_mem hC_mem

/-- If the units of `S` are active, so are the returns of child `c`. -/
theorem outGen_subset_closure {d : ℕ} {α P : Type*} (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (I : Set α) (c : Fin d) (S : Set α) (hS : S ⊆ FrogModel.Stage.closure gen π I) :
    outGen dir gen π isRoot sub c S ⊆ FrogModel.Stage.closure gen π I := by
  intro y hy
  rcases hy with ⟨hyRoot, x, hx, hxy⟩
  -- hx : x ∈ subClosure dir gen π isRoot sub c S
  -- hxy : gen x (π x) y
  have hx_closure : x ∈ FrogModel.Stage.closure gen π I := by
    -- x ∈ subClosure means x is in the intersection of all U containing {z∈S | isRoot z ∧ dir z = c.succ}
    -- and closed under (fun z p w => gen z p w ∧ sub c w)
    -- T = FrogModel.Stage.closure gen π I also satisfies these conditions
    rw [FrogModel.Stage.closure]
    -- Goal: x ∈ ⋂₀ {S | I ⊆ S ∧ ∀ σ ∈ S, ∀ τ, gen σ (π σ) τ → τ ∈ S}
    apply Set.mem_sInter.mpr
    intro T hT
    rcases hT with ⟨hIT, hTclosed⟩
    -- hIT : I ⊆ T, hTclosed : ∀ σ ∈ T, ∀ τ, gen σ (π σ) τ → τ ∈ T
    -- From hS, we have S ⊆ FrogModel.Stage.closure gen π I
    -- Since T contains I and is closed under gen, FrogModel.Stage.closure gen π I ⊆ T
    -- So S ⊆ T
    have hST : S ⊆ T := by
      intro z hz
      have hz_closure : z ∈ FrogModel.Stage.closure gen π I := hS hz
      -- Now use the definition of closure to get z ∈ T
      rw [FrogModel.Stage.closure] at hz_closure
      have hzT := Set.mem_sInter.mp hz_closure T ⟨hIT, hTclosed⟩
      exact hzT
    -- Now, x ∈ subClosure means x ∈ closure of {z∈S | isRoot z ∧ dir z = c.succ} under restricted gen
    -- But T itself is closed under restricted gen and contains that base set
    have hxT : x ∈ T := by
      rw [FrogModel.Recursion.subClosure] at hx
      -- hx : x ∈ FrogModel.Stage.closure (fun x p y => gen x p y ∧ sub c y) π {x | x ∈ S ∧ isRoot x ∧ dir x = c.succ}
      rw [FrogModel.Stage.closure] at hx
      apply Set.mem_sInter.mp hx T
      constructor
      · -- {x | x ∈ S ∧ isRoot x ∧ dir x = c.succ} ⊆ T
        intro z hz
        rcases hz with ⟨hzS, hzRoot, hzDir⟩
        exact hST hzS
      · -- T is closed under (fun x p y => gen x p y ∧ sub c y)
        intro σ hσT τ hgen_sub
        rcases hgen_sub with ⟨hgen, hsub⟩
        exact hTclosed σ hσT τ hgen
    exact hxT
  -- Now we have x ∈ FrogModel.Stage.closure gen π I and gen x (π x) y
  -- Need to show y ∈ FrogModel.Stage.closure gen π I
  rw [FrogModel.Stage.closure]
  apply Set.mem_sInter.mpr
  intro T hT
  rcases hT with ⟨hIT, hTclosed⟩
  -- From x ∈ closure, we know x ∈ T
  have hxT : x ∈ T := by
    rw [FrogModel.Stage.closure] at hx_closure
    exact Set.mem_sInter.mp hx_closure T ⟨hIT, hTclosed⟩
  -- Since T is closed under gen and gen x (π x) y, we get y ∈ T
  exact hTclosed x hxT y hxy

/-- The arrivals of the processing are active root units. -/
theorem arrSet_subset_closure {d : ℕ} {α P : Type*} (init : ℕ → α) (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (hinitRoot : ∀ a, isRoot (init a)) (j : ℕ) :
    arrSet init dir (outGen dir gen π isRoot sub) j ⊆
      {x | isRoot x} ∩ FrogModel.Stage.closure gen π (init '' {a | a < j}) := by
  set A := {x | isRoot x} ∩ FrogModel.Stage.closure gen π (init '' {a | a < j}) with hA
  have hI_sub_closure : init '' {a | a < j} ⊆ FrogModel.Stage.closure gen π (init '' {a | a < j}) :=
    Stage.subset_closure gen π (init '' {a | a < j})
  have hI_sub_A : init '' {a | a < j} ⊆ A := by
    intro x hx
    rcases hx with ⟨a, ha, rfl⟩
    exact ⟨hinitRoot a, hI_sub_closure ⟨a, ha, rfl⟩⟩
  have hout : ∀ c : Fin d, outGen dir gen π isRoot sub c {x | x ∈ A ∧ dir x = c.succ} ⊆ A := by
    intro c x hx
    have hroot : isRoot x := by
      unfold outGen at hx
      rcases hx with ⟨hroot', _⟩
      exact hroot'
    have hS : {x | x ∈ A ∧ dir x = c.succ} ⊆ FrogModel.Stage.closure gen π (init '' {a | a < j}) := by
      intro y hy
      rcases hy with ⟨hyA, _⟩
      exact hyA.2
    have hclosure : x ∈ FrogModel.Stage.closure gen π (init '' {a | a < j}) :=
      FrogModel.Recursion.outGen_subset_closure dir gen π isRoot sub (init '' {a | a < j}) c
        {x | x ∈ A ∧ dir x = c.succ} hS hx
    exact ⟨hroot, hclosure⟩
  exact FrogModel.Recursion.arrSet_subset init dir (outGen dir gen π isRoot sub) j A hI_sub_A hout

/-- Every active unit is an arrival or lies in the subtree closure of the arrivals. -/
theorem closure_subset_arrSet_union {d : ℕ} {α P : Type*} (init : ℕ → α)
    (dir : α → Fin (d + 1)) (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop)
    (sub : Fin d → α → Prop) (hinitRoot : ∀ a, isRoot (init a))
    (hroot0 : ∀ x y, isRoot x → dir x = 0 → ¬ gen x (π x) y)
    (hrootc : ∀ (c : Fin d) x y, isRoot x → dir x = c.succ → gen x (π x) y →
      isRoot y ∨ sub c y)
    (hsubc : ∀ (c : Fin d) x y, sub c x → gen x (π x) y → isRoot y ∨ sub c y) (j : ℕ) :
    FrogModel.Stage.closure gen π (init '' {a | a < j}) ⊆
      arrSet init dir (outGen dir gen π isRoot sub) j ∪
        ⋃ c : Fin d, subClosure dir gen π isRoot sub c
          (arrSet init dir (outGen dir gen π isRoot sub) j) := by
  set A := arrSet init dir (outGen dir gen π isRoot sub) j with hA
  set B := A ∪ ⋃ c : Fin d, subClosure dir gen π isRoot sub c A with hB
  -- Every element of A is a root unit
  have hA_root : A ⊆ {x | isRoot x} := by
    apply arrSet_subset init dir (outGen dir gen π isRoot sub) j {x | isRoot x}
    · intro x hx
      rcases hx with ⟨a, ha, rfl⟩
      exact hinitRoot a
    · intro c x hx
      exact hx.1
  -- outGen is monotone in the set argument
  have h_outGen_mono : ∀ c, Monotone (outGen dir gen π isRoot sub c) :=
    fun c => outGen_mono dir gen π isRoot sub c
  -- The subClosure bases for A and {x | x ∈ A ∧ dir x = c.succ} are equal
  have h_subClosure_base_eq (c : Fin d) :
      {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ} =
      {x | x ∈ {x | x ∈ A ∧ dir x = c.succ} ∧ isRoot x ∧ dir x = c.succ} := by
    ext x; constructor
    · rintro ⟨hxA, hx_root, hx_dir⟩; exact ⟨⟨hxA, hx_dir⟩, hx_root, hx_dir⟩
    · rintro ⟨⟨hxA, hx_dir⟩, hx_root, _⟩; exact ⟨hxA, hx_root, hx_dir⟩
  -- Hence subClosure c A = subClosure c {x | x ∈ A ∧ dir x = c.succ}
  have h_subClosure_eq (c : Fin d) :
      subClosure dir gen π isRoot sub c A =
      subClosure dir gen π isRoot sub c {x | x ∈ A ∧ dir x = c.succ} := by
    dsimp [subClosure]
    congr 1
    exact h_subClosure_base_eq c
  -- Hence outGen c A = outGen c {x | x ∈ A ∧ dir x = c.succ}
  have h_outGen_eq (c : Fin d) :
      outGen dir gen π isRoot sub c A =
      outGen dir gen π isRoot sub c {x | x ∈ A ∧ dir x = c.succ} := by
    dsimp [outGen]
    rw [h_subClosure_eq c]
  -- outGen c {x | x ∈ A ∧ dir x = c.succ} ⊆ A
  have h_outGen_sub_A (c : Fin d) :
      outGen dir gen π isRoot sub c {x | x ∈ A ∧ dir x = c.succ} ⊆ A :=
    out_subset_arrSet init dir (outGen dir gen π isRoot sub) h_outGen_mono j c
  -- Therefore outGen c A ⊆ A
  have h_outGen_A_sub_A (c : Fin d) : outGen dir gen π isRoot sub c A ⊆ A := by
    rw [h_outGen_eq c]
    exact h_outGen_sub_A c
  -- B is in the closure family
  have hB_mem : B ∈ {S : Set α | init '' {a | a < j} ⊆ S ∧ ∀ σ ∈ S, ∀ τ, gen σ (π σ) τ → τ ∈ S} := by
    refine ⟨?_, ?_⟩
    · -- base ⊆ B
      intro x hx
      rcases hx with ⟨a, ha, rfl⟩
      apply Set.mem_union_left
      exact init_mem_arrSet init dir (outGen dir gen π isRoot sub) ha
    · -- closed under arcs
      intro σ hσ τ hgen
      rcases hσ with (hσA | hσsub)
      · -- σ ∈ A
        have hσ_root : isRoot σ := hA_root hσA
        rcases Fin.eq_zero_or_eq_succ (dir σ) with (hdir0 | ⟨c, hdir_succ⟩)
        · -- dir σ = 0, impossible by hroot0
          exfalso; exact hroot0 σ τ hσ_root hdir0 hgen
        · -- dir σ = c.succ
          have hσ_in_subClosure : σ ∈ subClosure dir gen π isRoot sub c A := by
            apply FrogModel.Stage.subset_closure
              (fun x p y => gen x p y ∧ sub c y) π
              {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ}
            exact ⟨hσA, hσ_root, hdir_succ⟩
          rcases hrootc c σ τ hσ_root hdir_succ hgen with (hτ_root | hτ_sub)
          · -- isRoot τ, show τ ∈ B (via A)
            have hτ_in_A : τ ∈ A := h_outGen_A_sub_A c ⟨hτ_root, σ, hσ_in_subClosure, hgen⟩
            exact Set.mem_union_left _ hτ_in_A
          · -- sub c τ, show τ ∈ subClosure c A
            have hτ_in_subClosure : τ ∈ subClosure dir gen π isRoot sub c A :=
              FrogModel.Stage.closure_arc (fun x p y => gen x p y ∧ sub c y) π
                {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ} σ τ hσ_in_subClosure ⟨hgen, hτ_sub⟩
            apply Set.mem_union_right
            exact Set.mem_iUnion.mpr ⟨c, hτ_in_subClosure⟩
      · -- σ ∈ ⋃ c, subClosure c A
        rcases Set.mem_iUnion.mp hσsub with ⟨c, hσ_in_subClosure⟩
        rcases subClosure_subset dir gen π isRoot sub c A hσ_in_subClosure with
          (⟨hσA, hσ_root, hσ_dir⟩ | hσ_sub_c)
        · -- σ ∈ A, isRoot σ, dir σ = c.succ
          have hσ_in_subClosure' : σ ∈ subClosure dir gen π isRoot sub c A := by
            apply FrogModel.Stage.subset_closure
              (fun x p y => gen x p y ∧ sub c y) π
              {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ}
            exact ⟨hσA, hσ_root, hσ_dir⟩
          rcases hrootc c σ τ hσ_root hσ_dir hgen with (hτ_root | hτ_sub)
          · -- isRoot τ, show τ ∈ B (via A)
            have hτ_in_A : τ ∈ A := h_outGen_A_sub_A c ⟨hτ_root, σ, hσ_in_subClosure', hgen⟩
            exact Set.mem_union_left _ hτ_in_A
          · -- sub c τ, show τ ∈ subClosure c A
            have hτ_in_subClosure : τ ∈ subClosure dir gen π isRoot sub c A :=
              FrogModel.Stage.closure_arc (fun x p y => gen x p y ∧ sub c y) π
                {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ} σ τ hσ_in_subClosure' ⟨hgen, hτ_sub⟩
            apply Set.mem_union_right
            exact Set.mem_iUnion.mpr ⟨c, hτ_in_subClosure⟩
        · -- sub c σ
          rcases hsubc c σ τ hσ_sub_c hgen with (hτ_root | hτ_sub)
          · -- isRoot τ, show τ ∈ B (via A)
            have hτ_in_A : τ ∈ A := h_outGen_A_sub_A c ⟨hτ_root, σ, hσ_in_subClosure, hgen⟩
            exact Set.mem_union_left _ hτ_in_A
          · -- sub c τ, show τ ∈ subClosure c A
            have hτ_in_subClosure : τ ∈ subClosure dir gen π isRoot sub c A :=
              FrogModel.Stage.closure_arc (fun x p y => gen x p y ∧ sub c y) π
                {x | x ∈ A ∧ isRoot x ∧ dir x = c.succ} σ τ hσ_in_subClosure ⟨hgen, hτ_sub⟩
            apply Set.mem_union_right
            exact Set.mem_iUnion.mpr ⟨c, hτ_in_subClosure⟩
  -- Apply sInter_subset_of_mem
  have h := Set.sInter_subset_of_mem hB_mem
  simpa [FrogModel.Stage.closure] using h

/-- **The active root units are the arrivals.** -/
theorem arrSet_eq_closure {d : ℕ} {α P : Type*} (init : ℕ → α) (dir : α → Fin (d + 1))
    (gen : α → P → α → Prop) (π : α → P) (isRoot : α → Prop) (sub : Fin d → α → Prop)
    (hinitRoot : ∀ a, isRoot (init a)) (hsubRoot : ∀ c x, sub c x → ¬ isRoot x)
    (hroot0 : ∀ x y, isRoot x → dir x = 0 → ¬ gen x (π x) y)
    (hrootc : ∀ (c : Fin d) x y, isRoot x → dir x = c.succ → gen x (π x) y →
      isRoot y ∨ sub c y)
    (hsubc : ∀ (c : Fin d) x y, sub c x → gen x (π x) y → isRoot y ∨ sub c y) (j : ℕ) :
    arrSet init dir (outGen dir gen π isRoot sub) j =
      {x | isRoot x} ∩ FrogModel.Stage.closure gen π (init '' {a | a < j}) := by
  apply Set.Subset.antisymm
  · exact arrSet_subset_closure init dir gen π isRoot sub hinitRoot j
  · intro x hx
    rcases hx with ⟨hxRoot, hxClosure⟩
    have hxUnion := closure_subset_arrSet_union init dir gen π isRoot sub hinitRoot hroot0
      hrootc hsubc j hxClosure
    rcases hxUnion with (hxArr | hxSub)
    · exact hxArr
    · rcases Set.mem_iUnion.mp hxSub with ⟨c, hxSubClosure⟩
      have hxSub' := subClosure_subset dir gen π isRoot sub c
        (arrSet init dir (outGen dir gen π isRoot sub) j) hxSubClosure
      rcases hxSub' with (⟨hxArr', hxRoot', hxDir⟩ | hxSubc)
      · exact hxArr'
      · exact absurd hxRoot (hsubRoot c x hxSubc)

end FrogModel.Recursion
