// Labeled Markov classes of block laws (floating point; the certificate is checked elsewhere).
// A law of the class is generated by increments: B(1) from the root row, then
// B(q + 1) - B(q) from the row of (q, label_q), where label_q = (B(q), flag, extra) is updated by a
// fixed rule of the class from label_{q-1} and the increment. Any such law is a legitimate H*
// (Theorem 5.3 of the paper accepts any law); its child chain has the states (q, label) and is exact.
// kind 0: Markov in (q, B(q));
// kind 1: (q, B(q), all increments so far <= 1) ("smooth" flag);
// kind 2: (q, B(q), min(B(1), 2));
// kind 3: (q, B(q), smooth flag, min(B(1), 2)).
// Support: F_T = {B(J) <= T}; rows only put mass on increments that keep B(q) <= T.

use crate::fx::Map as HashMap;
pub const D: usize = 4;

pub type Lab = (u8, u8, u8);

pub fn root(kind: u8) -> Lab {
    match kind {
        1 | 3 => (0, 1, 0),
        _ => (0, 0, 0),
    }
}

pub fn next(kind: u8, q: usize, l: Lab, d: u8) -> Lab {
    let b = l.0 + d;
    let f = if kind == 1 || kind == 3 { (l.1 == 1 && d <= 1) as u8 } else { 0 };
    let x = if kind == 2 || kind == 3 {
        if q == 0 {
            d.min(2)
        } else {
            l.2
        }
    } else {
        0
    };
    (b, f, x)
}

#[derive(Clone)]
pub struct CL {
    pub j: usize,
    pub t: usize,
    pub kind: u8,
    pub labs: Vec<Vec<Lab>>,            // labs[q], q = 0..J-1 (labs[0] = [root])
    pub idx: Vec<HashMap<Lab, usize>>,  // position of a label in labs[q]
    pub rows: Vec<Vec<Vec<f64>>>,       // rows[q][k][d]: law of the increment at (q, labs[q][k])
    pub off: Vec<usize>,                // child id of (q, labs[q][k]) = 2 + off[q] + k, q = 1..J-1
    pub nid: usize,                     // number of non-tail child ids
}

impl CL {
    pub fn new(j: usize, t: usize, kind: u8) -> CL {
        let mut labs = vec![vec![root(kind)]];
        for q in 0..j - 1 {
            let mut nx: Vec<Lab> = Vec::new();
            for l in &labs[q] {
                for d in 0..=(t - l.0 as usize) {
                    let n = next(kind, q, *l, d as u8);
                    if !nx.contains(&n) {
                        nx.push(n);
                    }
                }
            }
            nx.sort();
            labs.push(nx);
        }
        let idx: Vec<HashMap<Lab, usize>> = labs.iter().map(|v| v.iter().enumerate().map(|(k, l)| (*l, k)).collect()).collect();
        let mut off = vec![0; j];
        let mut n = 0;
        for q in 1..j {
            off[q] = n;
            n += labs[q].len();
        }
        let rows = labs.iter().map(|v| v.iter().map(|_| vec![0.0; t + 1]).collect()).collect();
        CL { j, t, kind, labs, idx, rows, off, nid: 2 + n }
    }
    pub fn sid(&self, q: usize, l: Lab) -> u16 {
        if q == self.j {
            1
        } else {
            (2 + self.off[q] + self.idx[q][&l]) as u16
        }
    }
    pub fn tail_id(&self, q: usize) -> u16 {
        if q == self.j {
            1
        } else {
            (self.nid + q - 1) as u16
        }
    }
    pub fn nstates(&self) -> usize {
        self.nid + self.j - 1
    }
    pub fn chain(&self) -> Vec<Vec<(f64, u8, u16)>> {
        let (j, t) = (self.j, self.t);
        let mut tr = vec![Vec::new(); self.nid];
        let r0 = root(self.kind);
        // from F: the child's own frog and the entering frog use indices 1 and 2
        let mut acc: HashMap<(u8, u16), f64> = HashMap::default();
        for d1 in 0..=t {
            let p1 = self.rows[0][0][d1];
            if p1 <= 0.0 {
                continue;
            }
            let l1 = next(self.kind, 0, r0, d1 as u8);
            if j == 1 {
                continue;
            }
            let k1 = self.idx[1][&l1];
            for d2 in 0..=t {
                let p2 = self.rows[1][k1][d2];
                if p2 <= 0.0 {
                    continue;
                }
                let l2 = next(self.kind, 1, l1, d2 as u8);
                *acc.entry(((d1 + d2) as u8, self.sid(2, l2))).or_insert(0.0) += p1 * p2;
            }
            tr[1].push((p1, d1 as u8, self.sid(1, l1)));
        }
        let mut v: Vec<_> = acc.into_iter().map(|((dl, nx), p)| (p, dl, nx)).collect();
        v.sort_by(|a, b| (a.1, a.2).cmp(&(b.1, b.2)));
        tr[0] = v;
        for q in 1..j {
            for (k, l) in self.labs[q].iter().enumerate() {
                let id = 2 + self.off[q] + k;
                for d in 0..=t {
                    let p = self.rows[q][k][d];
                    if p > 0.0 {
                        tr[id].push((p, d as u8, self.sid(q + 1, next(self.kind, q, *l, d as u8))));
                    }
                }
            }
        }
        tr
    }
    pub fn joint(&self) -> HashMap<Vec<u8>, f64> {
        let mut cur: HashMap<(Vec<u8>, Lab), f64> = HashMap::default();
        cur.insert((vec![], root(self.kind)), 1.0);
        for q in 0..self.j {
            let mut nx: HashMap<(Vec<u8>, Lab), f64> = HashMap::default();
            for ((v, l), m) in cur {
                let k = self.idx[q][&l];
                for d in 0..=self.t {
                    let p = self.rows[q][k][d];
                    if p > 0.0 {
                        let mut v2 = v.clone();
                        v2.push(l.0 + d as u8);
                        *nx.entry((v2, next(self.kind, q, l, d as u8))).or_insert(0.0) += m * p;
                    }
                }
            }
            cur = nx;
        }
        let mut out: HashMap<Vec<u8>, f64> = HashMap::default();
        for ((v, _), m) in cur {
            *out.entry(v).or_insert(0.0) += m;
        }
        out
    }
    pub fn mean(&self, q: usize) -> f64 {
        self.joint().iter().map(|(v, m)| v[q - 1] as f64 * m).sum()
    }
    // extrapolation of every row's tail function along the step prev -> self, as check::extrapolate
    pub fn extrapolate(&self, prev: &CL, s: f64) -> CL {
        let t = self.t;
        let mut o = self.clone();
        for q in 0..self.j {
            for k in 0..self.labs[q].len() {
                let (a, b) = (&self.rows[q][k], &prev.rows[q][k]);
                if a.iter().sum::<f64>() <= 0.0 {
                    continue;
                }
                let lim = t - self.labs[q][k].0 as usize; // largest allowed increment
                let tail = |v: &[f64]| -> Vec<f64> {
                    let mut r = vec![0.0; t + 2];
                    for x in (0..=t).rev() {
                        r[x] = r[x + 1] + v[x];
                    }
                    r
                };
                let (ta, tb) = (tail(a), tail(b));
                let mut r = vec![0.0; t + 2];
                for x in 0..=t {
                    r[x] = if x == 0 { 1.0 } else if x > lim { 0.0 } else { (ta[x] + s * (ta[x] - tb[x])).clamp(0.0, 1.0) };
                    if x > 0 && r[x] > r[x - 1] {
                        r[x] = r[x - 1];
                    }
                }
                o.rows[q][k] = (0..=t).map(|x| r[x] - r[x + 1]).collect();
            }
        }
        o
    }
    pub fn save(&self, path: &str) {
        let mut s = format!("{} {} {}\n", self.j, self.t, self.kind);
        for q in 0..self.j {
            for (k, l) in self.labs[q].iter().enumerate() {
                s += &format!("{} {} {} {} :", q, l.0, l.1, l.2);
                s += &self.rows[q][k].iter().map(|x| format!(" {:e}", x)).collect::<String>();
                s += "\n";
            }
        }
        std::fs::write(path, s).unwrap();
    }
    pub fn load(path: &str) -> CL {
        let s = std::fs::read_to_string(path).unwrap();
        let mut ls = s.lines();
        let hd: Vec<usize> = ls.next().unwrap().split_whitespace().map(|x| x.parse().unwrap()).collect();
        let mut c = CL::new(hd[0], hd[1], hd[2] as u8);
        for l in ls {
            let (a, b) = l.split_once(':').unwrap();
            let h: Vec<u8> = a.split_whitespace().map(|x| x.parse().unwrap()).collect();
            let k = c.idx[h[0] as usize][&(h[1], h[2], h[3])];
            c.rows[h[0] as usize][k] = b.split_whitespace().map(|x| x.parse().unwrap()).collect();
        }
        c
    }
}

// potential of Lemma 6.3 of the paper for a class law: w(q, label) = kappa^(q-1) E[phi^(B(J) - B(q)) | label]
pub fn pot(h: &CL, eps: f64, phi: f64, rho: f64) -> crate::check::Pot {
    let (j, t) = (h.j, h.t);
    let mut r: Vec<Vec<f64>> = h.labs.iter().map(|v| vec![1.0; v.len()]).collect();
    for q in (0..j).rev() {
        for (k, l) in h.labs[q].iter().enumerate() {
            let mut s = 0.0;
            for d in 0..=t {
                let p = h.rows[q][k][d];
                if p > 0.0 {
                    let r2 = if q + 1 == j { 1.0 } else { r[q + 1][h.idx[q + 1][&next(h.kind, q, *l, d as u8)]] };
                    s += p * phi.powi(d as i32) * r2;
                }
            }
            r[q][k] = s;
        }
    }
    let m = (1.0 - eps) * r[0][0] + eps * (1.0 - rho) * phi.powi(t as i32 + 1) / (1.0 - phi * rho);
    let kappa = m.powf(1.0 / j as f64) * (1.0 + 1e-12);
    let theta = 5.0 * phi - 4.0 * kappa;
    let mut w = vec![0.0; h.nstates()];
    w[0] = kappa.powi(j as i32);
    w[1] = kappa.powi(j as i32 - 1);
    for q in 1..j {
        for (k, l) in h.labs[q].iter().enumerate() {
            w[h.sid(q, *l) as usize] = kappa.powi(q as i32 - 1) * r[q][k];
        }
        w[h.tail_id(q) as usize] = kappa.powi(q as i32 - 1);
    }
    crate::check::Pot { phi, theta, rho, m, w }
}

// Upper envelope in the class (a dominating class law built by a sequential coupling): given a
// law L on F_T (any total mass m), returns a class law H with L <= m H. Level by level it keeps
// the coupling pi_q of (x_1..x_q) under L and (y_1..y_q) under H, x <= y. For each H-prefix h,
// m_h = law of (X_{q+1} - y_q)^+ when x ~ pi_q(., h) and X_{q+1} ~ L(. | x); the row of a label
// is the stochastic maximum of the m_h over the prefixes h with that label (pointwise maximum
// of the tail functions); the pair is extended by the quantile coupling of m_h and the row.
// For the full-prefix class this returns L itself; the excess comes from the maximum.
pub fn envelope(l: &HashMap<Vec<u8>, f64>, j: usize, t: usize, kind: u8) -> CL {
    let mut h = CL::new(j, t, kind);
    // conditional laws of L: cond[x prefix] = law of the next coordinate (mass)
    let mut cond: HashMap<Vec<u8>, Vec<f64>> = HashMap::default();
    for (v, m) in l {
        for q in 0..j {
            let e = cond.entry(v[..q].to_vec()).or_insert_with(|| vec![0.0; t + 1]);
            e[v[q] as usize] += m;
        }
    }
    // pi: (x prefix, y prefix) -> mass
    let mut pi: HashMap<(Vec<u8>, Vec<u8>), f64> = HashMap::default();
    let tot: f64 = l.values().sum();
    pi.insert((vec![], vec![]), tot);
    for q in 0..j {
        // group by y prefix: components (x prefix, next x, increment u, mass)
        let mut byh: HashMap<Vec<u8>, Vec<(Vec<u8>, u8, usize, f64)>> = HashMap::default();
        for ((x, y), m) in &pi {
            let c = &cond[x];
            let cs: f64 = c.iter().sum();
            let yq = if q == 0 { 0 } else { y[q - 1] as usize };
            for (xn, w) in c.iter().enumerate() {
                if *w > 0.0 {
                    let u = xn.saturating_sub(yq);
                    byh.entry(y.clone()).or_default().push((x.clone(), xn as u8, u, m * w / cs));
                }
            }
        }
        // rows: maximum of the tail functions of the normalized m_h over h with the same label
        let lab_of = |y: &[u8]| -> Lab {
            let mut lb = root(kind);
            let mut prev = 0u8;
            for (i, v) in y.iter().enumerate() {
                lb = next(kind, i, lb, v - prev);
                prev = *v;
            }
            lb
        };
        let mut tails: HashMap<Lab, Vec<f64>> = HashMap::default();
        let mut mh: HashMap<Vec<u8>, Vec<f64>> = HashMap::default();
        for (y, comps) in &byh {
            let mut law = vec![0.0; t + 1];
            for (_, _, u, m) in comps {
                law[*u] += m;
            }
            let s: f64 = law.iter().sum();
            for x in law.iter_mut() {
                *x /= s;
            }
            let mut tl = vec![0.0; t + 2];
            for x in (0..=t).rev() {
                tl[x] = tl[x + 1] + law[x];
            }
            let e = tails.entry(lab_of(y)).or_insert_with(|| vec![0.0; t + 2]);
            for x in 0..=t {
                e[x] = e[x].max(tl[x]);
            }
            mh.insert(y.clone(), law);
        }
        for (k, lb) in h.labs[q].clone().iter().enumerate() {
            h.rows[q][k] = match tails.get(lb) {
                Some(tl) => (0..=t).map(|x| (tl[x] - tl[x + 1]).max(0.0)).collect(),
                None => (0..=t).map(|d| if d == 0 { 1.0 } else { 0.0 }).collect(),
            };
            let s: f64 = h.rows[q][k].iter().sum();
            for x in h.rows[q][k].iter_mut() {
                *x /= s;
            }
        }
        // extend the coupling: quantile coupling of m_h (with its components) and the row
        let mut npi: HashMap<(Vec<u8>, Vec<u8>), f64> = HashMap::default();
        for (y, comps) in &byh {
            let law = &mh[y];
            let row = &h.rows[q][h.idx[q][&lab_of(y)]];
            let yq = if q == 0 { 0 } else { y[q - 1] as usize };
            let ps: f64 = comps.iter().map(|c| c.3).sum();
            // cumulative distribution functions
            let cm: Vec<f64> = (0..=t).scan(0.0, |a, x| { *a += law[x]; Some(*a) }).collect();
            let cr: Vec<f64> = (0..=t).scan(0.0, |a, x| { *a += row[x]; Some(*a) }).collect();
            for (x, xn, u, m) in comps {
                // the atom u of m_h covers the quantiles (lo, hi]; split m over the row values
                let lo = if *u == 0 { 0.0 } else { cm[*u - 1] };
                let hi = cm[*u];
                if hi - lo <= 0.0 {
                    continue;
                }
                for v in 0..=t {
                    let a = if v == 0 { 0.0 } else { cr[v - 1] };
                    let b = cr[v];
                    let ov = (hi.min(b) - lo.max(a)).max(0.0);
                    if v < *u {
                        // only rounding can make the row fall below m_h here
                        assert!(ov <= 1e-12, "envelope row below m_h");
                        continue;
                    }
                    if ov > 0.0 {
                        let mut x2 = x.clone();
                        x2.push(*xn);
                        let mut y2 = y.clone();
                        y2.push((yq + v) as u8);
                        *npi.entry((x2, y2)).or_insert(0.0) += m * ov / (hi - lo);
                    }
                }
            }
            let _ = ps;
        }
        pi = npi;
    }
    // sanity: every coupled pair is ordered
    for (x, y) in pi.keys() {
        assert!(x.iter().zip(y.iter()).all(|(a, b)| a <= b), "envelope coupling not ordered");
    }
    h
}

// ---- writer of the table (version 3 of code/certificate/FORMAT.md) and of its atoms ----

// decimal big integers (base 1e9 limbs, little endian), enough for products of row numerators
#[derive(Clone)]
pub struct Big(Vec<u64>);
impl Big {
    pub fn from(x: u64) -> Big {
        let mut b = Big(vec![]);
        let mut x = x;
        while x > 0 {
            b.0.push(x % 1_000_000_000);
            x /= 1_000_000_000;
        }
        b
    }
    pub fn mul(&self, m: u64) -> Big {
        assert!(m < (1u64 << 32));
        let mut out = Vec::with_capacity(self.0.len() + 2);
        let mut carry = 0u64;
        for l in &self.0 {
            let v = l * m + carry;
            out.push(v % 1_000_000_000);
            carry = v / 1_000_000_000;
        }
        while carry > 0 {
            out.push(carry % 1_000_000_000);
            carry /= 1_000_000_000;
        }
        while out.last() == Some(&0) {
            out.pop();
        }
        Big(out)
    }
    pub fn dec(&self) -> String {
        if self.0.is_empty() {
            return "0".into();
        }
        let mut s = format!("{}", self.0[self.0.len() - 1]);
        for l in self.0.iter().rev().skip(1) {
            s += &format!("{:09}", l);
        }
        s
    }
}

impl CL {
    // rows as integers over 2^bits, each row summing to 2^bits exactly (largest remainders)
    pub fn rational_rows(&self, bits: u32) -> Vec<Vec<Vec<u64>>> {
        let den = 1u64 << bits;
        self.rows
            .iter()
            .map(|lv| {
                lv.iter()
                    .map(|r| {
                        let s: f64 = r.iter().sum();
                        let x: Vec<f64> = r.iter().map(|v| v / s * den as f64).collect();
                        let mut n: Vec<u64> = x.iter().map(|v| v.floor() as u64).collect();
                        let mut rem = den - n.iter().sum::<u64>();
                        let mut order: Vec<usize> = (0..r.len()).collect();
                        order.sort_by(|a, b| (x[*b] - x[*b].floor()).partial_cmp(&(x[*a] - x[*a].floor())).unwrap());
                        for &i in order.iter() {
                            if rem == 0 {
                                break;
                            }
                            if x[i] > 0.0 {
                                n[i] += 1;
                                rem -= 1;
                            }
                        }
                        assert_eq!(n.iter().sum::<u64>(), den);
                        n
                    })
                    .collect()
            })
            .collect()
    }
    // the class law with the rationalized rows (floating point copy, for the floating-point check)
    pub fn with_rows(&self, nr: &[Vec<Vec<u64>>], bits: u32) -> CL {
        let mut o = self.clone();
        let den = (1u64 << bits) as f64;
        for q in 0..self.j {
            for k in 0..self.labs[q].len() {
                o.rows[q][k] = nr[q][k].iter().map(|n| *n as f64 / den).collect();
            }
        }
        o
    }
    fn lname(&self, q: usize, l: Lab) -> String {
        if q == 0 {
            "root".into()
        } else if q == self.j {
            "end".into()
        } else {
            format!("b{}f{}x{}", l.0, l.1, l.2)
        }
    }
    // header lines common to both versions; eps = en/ed etc. as reduced fractions given by strings
    fn header(&self, eps: &str, rho: &str, phi: &str, kappa: &str, tpend: usize, rounds: usize, prune: &str) -> String {
        format!(
            "d 4\nJ {}\nT {}\nTpend {}\neps {}\nrho {}\nphi {}\nkappa {}\nrounds {}\nprune {}\n",
            self.j, self.t, tpend, eps, rho, phi, kappa, rounds, prune
        )
    }
    // v3 table: label and tr lines (rows over 2^bits)
    pub fn write_v3(&self, path: &str, bits: u32, hdr: (&str, &str, &str, &str, usize, usize, &str), _comment: &str) {
        let nr = self.rational_rows(bits);
        let mut s = format!("# The table of Section 7 of the paper, in the version 3 format of FORMAT.md: J = {}, T = {}, every probability a multiple of 2^-{}.\n", self.j, self.t, bits);
        s += &self.header(hdr.0, hdr.1, hdr.2, hdr.3, hdr.4, hdr.5, hdr.6);
        for q in 1..self.j {
            for l in &self.labs[q] {
                s += &format!("label {} {}\n", q, self.lname(q, *l));
            }
        }
        for q in 0..self.j {
            for (k, l) in self.labs[q].iter().enumerate() {
                for d in 0..=self.t {
                    let n = nr[q][k][d];
                    if n == 0 {
                        continue;
                    }
                    let l2 = next(self.kind, q, *l, d as u8);
                    let g = gcd(n, 1u64 << bits);
                    s += &format!("tr {} {} {} {} {}/{}\n", q, self.lname(q, *l), d, self.lname(q + 1, l2), n / g, (1u64 << bits) / g);
                }
            }
        }
        std::fs::write(path, s).unwrap();
    }
    // v2 atoms: h(B) = (1 - eps) P_tab(B) exactly, eps = en/ed; only atoms in F_T (kinds 0 to 3 stay in F_T)
    pub fn write_v2(&self, path: &str, bits: u32, en: u64, ed: u64, hdr: (&str, &str, &str, &str, usize, usize, &str), comment: &str) {
        let nr = self.rational_rows(bits);
        let mut s = format!("# {}\n# version 2 atoms of the class law (kind {}), h(B) = (1 - eps) P_tab(B) exactly\n", comment, self.kind);
        s += &self.header(hdr.0, hdr.1, hdr.2, hdr.3, hdr.4, hdr.5, hdr.6);
        // enumerate label paths, accumulate masses per vector as big numerators over ed 2^(bits J)
        // (distinct paths give distinct vectors for deterministic label rules)
        let mut cur: Vec<(Vec<u8>, Lab, Big)> = vec![(vec![], root(self.kind), Big::from(ed - en))];
        for q in 0..self.j {
            let mut nx = Vec::new();
            for (v, l, m) in cur {
                let k = self.idx[q][&l];
                for d in 0..=self.t {
                    let n = nr[q][k][d];
                    if n == 0 {
                        continue;
                    }
                    let mut v2 = v.clone();
                    v2.push(l.0 + d as u8);
                    nx.push((v2, next(self.kind, q, l, d as u8), m.mul(n)));
                }
            }
            cur = nx;
        }
        let mut den = Big::from(ed);
        for _ in 0..self.j {
            den = den.mul(1u64 << bits);
        }
        let dd = den.dec();
        let mut seen = std::collections::HashSet::new();
        for (v, _, m) in &cur {
            assert!(seen.insert(v.clone()), "two label paths give the same vector");
            s += &format!("h {} {}/{}\n", v.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(" "), m.dec(), dd);
        }
        std::fs::write(path, s).unwrap();
    }
}

fn gcd(a: u64, b: u64) -> u64 {
    if b == 0 {
        a
    } else {
        gcd(b, a % b)
    }
}
