\\ Writes FrogModel/D3/LaneE/Table.lean: the 95 intervals of the table of Proposition 15.2 of the paper, read from
\\ dcheck_m1_cert.gp, as `Entry` literals (FrogModel/D3/LaneE/Interval.lean), one kernel check per entry, the link
\\ of the table, and `dcheck1_holds : dcheck1`.
\\ Entry fields: ml = M(i), mh = M(i + 1) (M(i) = round(10^(5.5 + i/4)), i = 3..97), J, D, h = a/2 (k = a J,
\\ y = (3/2) k 3^(D-1) = 3 h J 3^(D-1)), a9, and sD, s1: the dyadic upper bounds (isqrt(floor(mu 4^64)) + 1)/2^64 of
\\ sqrt(mu_(ml+1-D)(1)) and sqrt(mu_ml(1)), mu_n(1) = (n + 2)/3.
\\ Usage: gp -q dcheck_m1_cert.gp gen_table.gp < /dev/null (from code/dcheck).
OUT = "../../FrogModel/D3/LaneE/Table.lean";
M(i) = my(f = sqrtint(sqrtint(16*10^(22 + i)))); (f + 1) \ 2;
if (M(3) != 1778279 || M(98) != 10^30 || #CERT != 95, error("interval data"));
squp(x) = (sqrtint(floor(x * 4^64)) + 1) / 2^64;
rq(x) = Str(numerator(x), " / ", denominator(x));
system(Str("rm -f ", OUT));
w(s) = write(OUT, s);
w("module\n\npublic import FrogModel.D3.LaneE.Pick\npublic import FrogModel.D3.Interfaces.Checks\n\n@[expose] public section\n");
w("/-!\n# The table of Proposition 15.2 of the paper and `dcheck1`\n");
w("Generated by code/dcheck/gen_table.gp from code/dcheck/dcheck_m1_cert.gp; do not");
w("edit. `eI` is the interval `[M(I), M(I + 1)]`, `M(I) = round(10^(5.5 + I/4))`, with the entry of the certificate");
w("(`h = a/2`) and the square-root bounds; `eI_check` is its check by the kernel. The parameter functions read the entry");
w("of a height with `pickE`.\n-/\n\nopen FrogModel.D3.Iface\n\nnamespace FrogModel.D3.LaneE\n");
{
for (t = 1, 95,
  my(i = t + 2, c = CERT[t], J = c[1], D = c[2], a = c[3], b = c[4], a9 = c[5], ml = M(i), mh = M(i + 1));
  if (b != 3/2 || a % 2, error("entry form"));
  my(muD = (ml + 3 - D)/3, mu1 = (ml + 2)/3);
  w(Str("def e", i, " : Entry := ⟨", ml, ", ", mh, ", ", J, ", ", D, ", ", a/2, ", ", a9, ", ", rq(squp(muD)), ", ", rq(squp(mu1)), "⟩"));
  w(Str("theorem e", i, "_check : e", i, ".check = true := by decide +kernel\n")));
}
{
my(s = "def rest : List Entry := [");
for (i = 4, 97, s = Str(s, "e", i, if(i < 97, ", ", "]")));
w(s);
w("\ntheorem linked_tbl : linked e3 rest = true := by decide +kernel\n");
s = "theorem rest_check : rest.all Entry.check = true := by\n  simp only [rest, List.all_cons, List.all_nil";
for (i = 4, 97, s = Str(s, ", e", i, "_check"));
w(Str(s, ", Bool.and_true]\n"));
w("/-- The comparison index of the height `m` on `[m1, 10^30]`. -/\ndef Jf (m : ℕ) : ℕ := (pickE rest e3 m).J");
w("/-- The depth of the height `m`. -/\ndef Df (m : ℕ) : ℕ := (pickE rest e3 m).D");
w("/-- `k(m)`. -/\ndef kf (m : ℕ) : ℕ := (pickE rest e3 m).k");
w("/-- `y(m)`. -/\ndef yf (m : ℕ) : ℕ := (pickE rest e3 m).y");
w("/-- `k1(m)`. -/\ndef k1f (m : ℕ) : ℕ := (pickE rest e3 m).k1\n");
w("theorem Jf_m1 : Jf m1 = 62 := by decide +kernel\n\ntheorem Jf_top : Jf (10 ^ 30) ≤ 140 := by decide +kernel\n");
w("/-- Proposition 15.2 of the paper. -/");
w("theorem dcheck1_holds : dcheck1 := by");
w("  refine ⟨Jf, Df, kf, yf, k1f, Jf_m1, (pickE_J_mono rest e3 linked_tbl).monotoneOn _, Jf_top, ?_⟩");
w("  intro m hm1 hm2");
w("  obtain ⟨hmem, hml, hmh⟩ := pickE_spec rest e3 m linked_tbl hm1 hm2");
w("  have hc : (pickE rest e3 m).check = true := by");
w("    rcases hmem with h | h");
w("    · rw [h]; exact e3_check");
w("    · exact List.all_eq_true.mp rest_check _ h");
w("  exact Entry.sound _ hc m hml hmh Jf Df kf yf k1f rfl rfl rfl rfl rfl\n");
w("end FrogModel.D3.LaneE");
}
print("wrote ", OUT);
